package summer.runtime;

import summer.core.RuntimeDiMarker;
import summer.core.annotation.Bean;
import summer.core.annotation.ConditionalOnBean;
import summer.core.annotation.Configuration;
import summer.core.config.ConfigurationBinder;
import summer.core.config.PageableProperties;

/**
 * Configuration for pagination support.
 *
 * <p>
 * Provides {@link PageableResolver} with configurable defaults. Defaults are
 * defined via {@link DefaultValue} annotations on {@link PageableProperties}
 * record components.
 * </p>
 *
 * <p>
 * Only active when the runtime DI engine is in use (i.e.,
 * {@link RuntimeDiMarker} is present). In AOT mode, pagination is handled by
 * inline code generated by {@code RouteAdapterGenerator}.
 * </p>
 *
 * <p>
 * Example YAML:
 * </p>
 *
 * <pre>{@code
 * summer:
 *   pageable:
 *     default-page: 0
 *     default-size: 20
 * }</pre>
 */
@Configuration
@ConditionalOnBean(RuntimeDiMarker.class)
public class PageableConfiguration {

	@Bean
	public PageableProperties pageableProperties() {
		return ConfigurationBinder.bind(PageableProperties.class, "summer.pageable");
	}

	@Bean
	public PageableResolver pageableResolver(PageableProperties props) {
		return new PageableResolver(props.defaultPage(), props.defaultSize());
	}
}
