package summer.plugin;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.TypeVariableName;
import com.palantir.javapoet.WildcardTypeName;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generates a {@code GeneratedAotContext} class that implements
 * {@code ApplicationContext}, wiring all discovered beans at compile time.
 */
public final class AotContextGenerator {

	public static final String PACKAGE = "summer.core.aot";
	public static final String CLASS_NAME = "GeneratedAotContext";

	private static final ClassName APPLICATION_CONTEXT = ClassName.get("summer.core", "ApplicationContext");
	private static final ClassName SUMMER_EXCEPTION = ClassName.get("summer.core", "SummerException");
	private static final ClassName ERROR_CODE = ClassName.get("summer.core", "ErrorCode");

	TypeName parseTypeName(String typeName) {
		int genericStart = typeName.indexOf('<');
		if (genericStart < 0) {
			return ClassName.bestGuess(typeName);
		}
		String rawType = typeName.substring(0, genericStart);
		return ClassName.bestGuess(rawType);
	}

	public void generate(List<BeanDefinition> sortedBeans, java.io.File outputDir) throws java.io.IOException {
		JavaFile javaFile = buildJavaFile(sortedBeans);
		javaFile.writeTo(outputDir);
	}

	private JavaFile buildJavaFile(List<BeanDefinition> sortedBeans) {
		TypeSpec contextClass = TypeSpec.classBuilder(CLASS_NAME)
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC, javax.lang.model.element.Modifier.FINAL)
				.addSuperinterface(APPLICATION_CONTEXT)
				.addJavadoc("Auto-generated AOT context. Do not edit manually!\n")
				.addJavadoc("Generated by summer-maven-plugin at compile time.\n").addField(buildSingletonsField())
				.addField(buildCloseablesField()).addMethod(buildConstructor()).addMethod(buildWireMethod(sortedBeans))
				.addMethod(buildGetBean()).addMethod(buildGetBeansOfType()).addMethod(buildGetComponentClasses())
				.addMethod(buildDestroy()).build();

		return JavaFile.builder(PACKAGE, contextClass)
				.addFileComment("Auto-generated by summer-maven-plugin. Do not edit!").indent("    ").build();
	}

	private FieldSpec buildSingletonsField() {
		ParameterizedTypeName mapType = ParameterizedTypeName.get(ClassName.get(Map.class),
				ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)),
				ClassName.get(Object.class));
		return FieldSpec.builder(mapType, "singletons", javax.lang.model.element.Modifier.PRIVATE,
				javax.lang.model.element.Modifier.FINAL).initializer("new $T<>()", LinkedHashMap.class).build();
	}

	private FieldSpec buildCloseablesField() {
		ParameterizedTypeName listType = ParameterizedTypeName.get(ClassName.get(List.class),
				ClassName.get(AutoCloseable.class));
		return FieldSpec.builder(listType, "closeables", javax.lang.model.element.Modifier.PRIVATE,
				javax.lang.model.element.Modifier.FINAL).initializer("new $T<>()", ArrayList.class).build();
	}

	private MethodSpec buildConstructor() {
		return MethodSpec.constructorBuilder().addModifiers(javax.lang.model.element.Modifier.PUBLIC)
				.addStatement("wire()").build();
	}

	private MethodSpec buildWireMethod(List<BeanDefinition> sortedBeans) {
		MethodSpec.Builder wire = MethodSpec.methodBuilder("wire")
				.addModifiers(javax.lang.model.element.Modifier.PRIVATE);
		new WireMethodGenerator(this).generateWireMethod(wire, sortedBeans);
		return wire.build();
	}

	private MethodSpec buildGetBean() {
		TypeVariableName typeVar = TypeVariableName.get("T");
		return MethodSpec.methodBuilder("getBean").addAnnotation(Override.class)
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC).addTypeVariable(typeVar).returns(typeVar)
				.addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), typeVar), "type")
				.addStatement("$T bean = singletons.get(type)", Object.class).beginControlFlow("if (bean != null)")
				.addStatement("return (T) bean").endControlFlow()
				.addStatement("throw new $T($T.BEAN_NOT_FOUND, $S + type.getName())", SUMMER_EXCEPTION, ERROR_CODE,
						"No bean found of type: ")
				.build();
	}

	private MethodSpec buildGetBeansOfType() {
		TypeVariableName typeVar = TypeVariableName.get("T");
		return MethodSpec.methodBuilder("getBeansOfType").addAnnotation(Override.class)
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC).addTypeVariable(typeVar)
				.returns(ParameterizedTypeName.get(ClassName.get(List.class), typeVar))
				.addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), typeVar), "type")
				.addStatement("return singletons.values().stream()\n"
						+ "    .filter(type::isInstance).map(v -> (T) v).toList()")
				.build();
	}

	private MethodSpec buildGetComponentClasses() {
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(Set.class),
				ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)));
		return MethodSpec.methodBuilder("getComponentClasses").addAnnotation(Override.class)
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC).returns(returnType)
				.addStatement("return singletons.keySet()").build();
	}

	private MethodSpec buildDestroy() {
		return MethodSpec.methodBuilder("destroy").addAnnotation(Override.class)
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC)
				.addStatement("var reversed = new $T<>(closeables)", ArrayList.class)
				.addStatement("$T.reverse(reversed)", Collections.class).beginControlFlow("for (var c : reversed)")
				.beginControlFlow("try").addStatement("c.close()").nextControlFlow("catch ($T e)", Exception.class)
				.addStatement("$T.err.println($S + e)", System.class, "[Summer] Error closing: ").endControlFlow()
				.endControlFlow().build();
	}
}
