package summer.aot;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.io.IOException;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import summer.core.bean.BeanDefinition;

/**
 * Generates a minimal AOT {@code BeanContainer} for a test class annotated with
 * {@code @SummerTest(engine = AOT, value = {...})}.
 *
 * <p>
 * Transitive dependency closure is computed by
 * {@link summer.core.bean.BeanClosure}; this class focuses solely on generating
 * the {@code LocalContext_<testClassName>} source file.
 * </p>
 */
public final class LocalContextGenerator {

	private static final Logger log = LoggerFactory.getLogger(LocalContextGenerator.class);

	private static final String PACKAGE = "summer.core.aot";

	private final WireMethodGenerator wireGen;
	private final java.io.File outputDir;

	public LocalContextGenerator(WireMethodGenerator wireGen, java.io.File outputDir) {
		this.wireGen = wireGen;
		this.outputDir = outputDir;
	}

	// ---- code generation (mirrors AotContextGenerator) ---------------------

	private static final String CORE_PACKAGE = "summer.core";
	private static final ClassName CN_BEAN_CONTAINER = ClassName.get(CORE_PACKAGE, "BeanContainer");
	private static final ClassName CN_BEAN_CONTAINER_BUILDER = ClassName.get(CORE_PACKAGE, "BeanContainer", "Builder");
	private static final ClassName CN_ENGINE = ClassName.get(CORE_PACKAGE, "Engine");
	private static final ClassName CN_AOT_DI_MARKER = ClassName.get(CORE_PACKAGE, "AotDiMarker");
	private static final ClassName CN_CONFIG_BINDER = ClassName.get("summer.core.config", "ConfigBinder");
	private static final ClassName CN_DEFAULT_VALUE_RESOLVER = ClassName.get("summer.core.config",
			"DefaultValueResolver");

	/**
	 * Generates a {@code LocalContext_<testClassName>} source file containing only
	 * the beans identified by the scoped discovery.
	 *
	 * @param testClassName
	 *            fully-qualified name of the test class
	 * @param sortedBeans
	 *            topologically-sorted beans in the closure
	 */
	public void generate(String testClassName, List<BeanDefinition> sortedBeans) throws IOException {

		String safeName = "LocalContext_" + testClassName.replace('.', '_').replace('$', '_');

		TypeSpec contextClass = TypeSpec.classBuilder(safeName)
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC, javax.lang.model.element.Modifier.FINAL)
				.addMethod(buildCreateMethod(sortedBeans))
				.addJavadoc("Generated by summer-maven-plugin for test class: " + testClassName + "\n").build();

		JavaFile javaFile = JavaFile.builder(PACKAGE, contextClass)
				.addFileComment("Auto-generated by summer-maven-plugin. Do not edit!").indent("    ").build();
		javaFile.writeTo(outputDir);

		log.debug("[Summer] Generated LocalContext for {} ({} beans)", testClassName, sortedBeans.size());
	}
	private MethodSpec buildCreateMethod(List<BeanDefinition> sortedBeans) {
		MethodSpec.Builder method = MethodSpec.methodBuilder("build")
				.addModifiers(javax.lang.model.element.Modifier.PUBLIC, javax.lang.model.element.Modifier.STATIC)
				.returns(CN_BEAN_CONTAINER).addException(Exception.class);

		method.addStatement("$T builder = new $T()", CN_BEAN_CONTAINER_BUILDER, CN_BEAN_CONTAINER_BUILDER);
		method.addStatement("builder.register($T.class, new $T())", CN_AOT_DI_MARKER, CN_AOT_DI_MARKER);

		method.addCode("\n");
		method.addComment("Setup @DefaultValue resolver");
		method.addStatement("$T.setDefaultValueResolver(($T) Class.forName($S).getField($S).get(null))",
				CN_CONFIG_BINDER, CN_DEFAULT_VALUE_RESOLVER, "summer.runtime.RuntimeDefaultValueResolver", "INSTANCE");
		method.addCode("\n");

		wireGen.generateWireMethod(method, sortedBeans);
		// Route adapter
		boolean hasControllers = sortedBeans.stream().anyMatch(b -> !b.routes.isEmpty());
		if (hasControllers) {
			method.addCode("\n");
			method.addComment("Register route adapter");
			method.addStatement("$T _routeAdapter = new $T()",
					ClassName.get("summer.core.aot", "GeneratedAnnotationRouterAdapter"),
					ClassName.get("summer.core.aot", "GeneratedAnnotationRouterAdapter"));
			method.addStatement("builder.register($T.class, _routeAdapter)",
					ClassName.get("summer.web", "RouteRegistrar"));
		}

		// Exception handler adapter — always present (empty if no handlers)
		method.addCode("\n");
		method.addComment("Register exception handler adapter");
		method.addStatement("$T _ehAdapter = new $T()",
				ClassName.get("summer.core.aot", "GeneratedExceptionHandlerAdapter"),
				ClassName.get("summer.core.aot", "GeneratedExceptionHandlerAdapter"));
		method.addStatement("builder.register($T.class, _ehAdapter)",
				ClassName.get("summer.web", "ExceptionHandlerRegistrar"));

		method.addCode("\n");
		method.addStatement("return builder.build($T.AOT)", CN_ENGINE);

		return method.build();
	}
}
