package summer.aot.generator;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.lang.model.element.Modifier;
import org.jboss.jandex.IndexView;

/**
 * Generates the AOT entry point class that aggregates all bean instantiations.
 *
 * <p>
 * The generated class implements {@code SummerBootstrap} and is discovered by
 * {@code SummerApplication} via {@code Class.forName}. The {@code launch()}
 * method creates the {@code BeanContainer} directly.
 * </p>
 */
public final class AppBootstrapGenerator {

	private static final ClassName BEAN_CONTAINER = ClassName.get("summer.core", "BeanContainer");
	private static final ClassName BEAN_REGISTRY = ClassName.get("summer.core", "BeanRegistry");
	private static final ClassName AOT_DI_MARKER = ClassName.get("summer.core", "AotDiMarker");
	private static final ClassName VALIDATOR = ClassName.get("summer.core.validation", "Validator");
	private static final ClassName SUMMER_BOOTSTRAP = ClassName.get("summer.boot", "SummerBootstrap");
	private static final ClassName CONFIG_BINDER = ClassName.get("summer.core.config", "ConfigBinder");

	public void generate(List<BeanDefinition> sorted, IndexView index, File outputDir) throws IOException {
		TypeSpec.Builder classBuilder = TypeSpec.classBuilder("AppBootstrap")
				.addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addSuperinterface(SUMMER_BOOTSTRAP)
				.addJavadoc("Auto-generated AOT entry point. Aggregates and flattens all beans globally.\n")
				.addJavadoc("Generated by summer-maven-plugin at compile time. Do not edit!\n");

		classBuilder.addMethod(buildLaunchMethod(sorted));

		JavaFile javaFile = JavaFile.builder("summer.core.aot", classBuilder.build())
				.addFileComment("Auto-generated by summer-maven-plugin. Do not edit!")
				.indent("    ")
				.build();
		javaFile.writeTo(outputDir);
	}

	private MethodSpec buildLaunchMethod(List<BeanDefinition> sorted) {
		MethodSpec.Builder method = MethodSpec.methodBuilder("launch")
				.addModifiers(Modifier.PUBLIC)
				.addException(Exception.class)
				.returns(BEAN_CONTAINER);

		method.addStatement("$T registry = new $T()", BEAN_REGISTRY, BEAN_REGISTRY);
		method.addStatement("registry.registerSingleton($T.class, new $T())", AOT_DI_MARKER, AOT_DI_MARKER);

		// Set up DefaultValueResolver for @ConfigurationProperties binding
		method.addComment("Setup @DefaultValue resolver (no-op if no @ConfigurationProperties exist)");
		method.beginControlFlow("try");
		method.addStatement("$T.setDefaultValueResolver(($T) Class.forName($S).getConstructor().newInstance())",
				CONFIG_BINDER,
				ClassName.get("summer.core.config", "DefaultValueResolver"),
				"summer.core.aot.AotDefaultValueResolver");
		method.nextControlFlow("catch ($T ignored)", ClassNotFoundException.class);
		method.endControlFlow();
		method.addCode("\n");

		// Flattened global bean instantiation
		for (BeanDefinition bean : sorted) {
			ClassName beanClass = ClassName.bestGuess(bean.qualifiedName);
			String varName = bean.variableName;

			if (bean instanceof ConfigPropertiesBean cpb) {
				method.addStatement("$T $N = ($T) $T.bind($S, $T.class)",
						beanClass, varName, beanClass, CONFIG_BINDER, cpb.configPropertiesPrefix, beanClass);
			} else if (bean instanceof FactoryBean fb) {
				ClassName configClass = ClassName.bestGuess(fb.configClassName);
				CodeBlock args = buildArgs(bean.argExpressions);
				method.addStatement("$T $N = (($T) registry.peek($T.class)).$L($L)",
						beanClass, varName, configClass, configClass, fb.producerMethodName, args);
			} else if (bean instanceof ComponentBean cb) {
				CodeBlock args = buildArgs(bean.argExpressions);
				method.addStatement("$T $N = new $T($L)", beanClass, varName, beanClass, args);
			}

			// Wrap in AOP proxy if needed
			if (bean instanceof ComponentBean cb && cb.needsProxy) {
				ClassName proxyClass = ClassName.get(TypeNameUtil.packageName(cb.qualifiedName), cb.simpleName + "$$AotProxy");
				CodeBlock.Builder interceptors = CodeBlock.builder();
				interceptors.add("$T.of(", java.util.List.class);
				for (int i = 0; i < cb.interceptors.size(); i++) {
					if (i > 0) interceptors.add(", ");
					interceptors.add("$N", cb.interceptors.get(i).variableName);
				}
				interceptors.add(")");
				method.addStatement("$T $N = new $T($N, $L)", proxyClass, varName + "_proxy", proxyClass, varName, interceptors.build());
				method.addStatement("registry.registerSingleton($T.class, $N)", beanClass, varName + "_proxy");
				for (String iface : bean.interfaceNames) {
					ClassName ifaceClass = ClassName.bestGuess(iface);
					method.beginControlFlow("if (registry.peek($T.class) == null)", ifaceClass);
					method.addStatement("registry.registerSingleton($T.class, $N_proxy)", ifaceClass, varName);
					method.endControlFlow();
				}
			} else {
				method.addStatement("registry.registerSingleton($T.class, $N)", beanClass, varName);
				for (String iface : bean.interfaceNames) {
					ClassName ifaceClass = ClassName.bestGuess(iface);
					method.beginControlFlow("if (registry.peek($T.class) == null)", ifaceClass);
					method.addStatement("registry.registerSingleton($T.class, $N)", ifaceClass, varName);
					method.endControlFlow();
				}
			}
			method.addCode("\n");
		}

		method.addStatement("$T ctx = $T.create(registry)", BEAN_CONTAINER, BEAN_CONTAINER);

		// Validation Phase
		method.addCode("\n");
		method.addComment("Validation Phase");
		method.beginControlFlow("for ($T validator : ctx.getBeans($T.class))", VALIDATOR, VALIDATOR);
		method.beginControlFlow("try");
		method.addStatement("$T target = ctx.getBean(validator.targetType())", Object.class);
		method.beginControlFlow("if (target != null)");
		method.addStatement("validator.validate(target)");
		method.endControlFlow();
		method.nextControlFlow("catch ($T e)", Exception.class);
		method.addStatement("throw new $T($S + e.getMessage(), e)",
				ClassName.get("summer.core.exception", "SummerException"), "Validation failed: ");
		method.endControlFlow();
		method.endControlFlow();

		method.addStatement("return ctx");
		return method.build();
	}

	private CodeBlock buildArgs(List<CodeBlock> argExpressions) {
		CodeBlock.Builder args = CodeBlock.builder();
		for (int i = 0; i < argExpressions.size(); i++) {
			if (i > 0) args.add(", ");
			args.add(argExpressions.get(i));
		}
		return args.build();
	}
}
