package summer.aot.generator;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;
import java.io.File;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.lang.model.element.Modifier;

/**
 * Generates an AOT {@code DefaultValueResolver} that applies
 * {@code @DefaultValue} defaults without reflection.
 */
public final class DefaultValueResolverGenerator {

	private static final ClassName DEFAULT_VALUE_RESOLVER = ClassName.get("summer.core.config", "DefaultValueResolver");
	private static final ClassName TYPE_CONVERTER = ClassName.get("summer.core.config", "TypeConverter");
	private static final ClassName LINKED_HASH_MAP = ClassName.get(LinkedHashMap.class);

	public String generate(List<ConfigPropertiesBean> configProperties, File outputDir) throws IOException {
		boolean hasDefaults = configProperties.stream().anyMatch(b -> !b.defaultValues.isEmpty());
		if (!hasDefaults) {
			return null;
		}

		TypeSpec.Builder classBuilder = TypeSpec.classBuilder("AotDefaultValueResolver")
				.addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addSuperinterface(DEFAULT_VALUE_RESOLVER);

		ParameterizedTypeName defaultsMapType = ParameterizedTypeName.get(ClassName.get(Map.class),
				ClassName.get(String.class),
				ParameterizedTypeName.get(ClassName.get(Map.class), ClassName.get(String.class),
						ClassName.get(Object.class)));
		classBuilder.addField(com.palantir.javapoet.FieldSpec.builder(defaultsMapType, "DEFAULTS",
				Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
				.initializer("new $T<>()", LINKED_HASH_MAP)
				.build());

		classBuilder.addMethod(buildApplyDefaultsMethod(configProperties));
		classBuilder.addStaticBlock(buildStaticInitializer(configProperties));

		JavaFile.builder("summer.core.aot", classBuilder.build())
				.addFileComment("Auto-generated by summer-maven-plugin. Do not edit!")
				.indent("    ")
				.build()
				.writeTo(outputDir);

		return "summer.core.aot.AotDefaultValueResolver";
	}

	private MethodSpec buildApplyDefaultsMethod(List<ConfigPropertiesBean> configProperties) {
		ParameterizedTypeName mapType = ParameterizedTypeName.get(ClassName.get(Map.class),
				ClassName.get(String.class), ClassName.get(Object.class));

		MethodSpec.Builder method = MethodSpec.methodBuilder("applyDefaults")
				.addAnnotation(Override.class)
				.addModifiers(Modifier.PUBLIC)
				.addParameter(mapType, "section")
				.addParameter(ParameterizedTypeName.get(ClassName.get(Class.class),
						com.palantir.javapoet.WildcardTypeName.subtypeOf(Object.class)), "type");

		for (ConfigPropertiesBean bean : configProperties) {
			if (bean.defaultValues.isEmpty())
				continue;
			ClassName beanClass = TypeNameUtil.classNameFromString(bean.qualifiedName);
			method.beginControlFlow("if (type == $T.class)", beanClass);
			method.addStatement("$T<$T, $T> d = DEFAULTS.get($S)",
					ClassName.get(Map.class), ClassName.get(String.class), ClassName.get(Object.class),
					bean.qualifiedName);
			method.beginControlFlow("if (d != null)");
			method.beginControlFlow("for (var e : d.entrySet())");
			method.beginControlFlow("if (!section.containsKey(e.getKey()))");
			method.addStatement("section.put(e.getKey(), e.getValue())");
			method.endControlFlow();
			method.endControlFlow();
			method.endControlFlow();
			method.addStatement("return");
			method.endControlFlow();
		}
		method.addStatement("return");
		return method.build();
	}

	private CodeBlock buildStaticInitializer(List<ConfigPropertiesBean> configProperties) {
		CodeBlock.Builder init = CodeBlock.builder();

		for (ConfigPropertiesBean bean : configProperties) {
			if (bean.defaultValues.isEmpty())
				continue;
			init.add("{\n");
			init.indent();
			init.add("$T<$T, $T> m = new $T<>()\n",
					ClassName.get(Map.class), ClassName.get(String.class), ClassName.get(Object.class),
					LINKED_HASH_MAP);
			init.add(";\n");
			for (var entry : bean.defaultValues.entrySet()) {
				String fieldName = entry.getKey();
				String rawValue = entry.getValue();
				String typeName = bean.fieldTypes.get(fieldName);
				ClassName boxedType = boxedClassName(typeName);
				init.add("m.put($S, $T.convert($S, $T.class));\n", fieldName, TYPE_CONVERTER, rawValue, boxedType);
			}
			init.add("DEFAULTS.put($S, m);\n", bean.qualifiedName);
			init.unindent();
			init.add("}\n");
		}
		return init.build();
	}

	private static ClassName boxedClassName(String typeName) {
		return switch (typeName) {
			case "java.lang.Boolean", "boolean" -> ClassName.get(Boolean.class);
			case "java.lang.Integer", "int" -> ClassName.get(Integer.class);
			case "java.lang.Long", "long" -> ClassName.get(Long.class);
			case "java.lang.Double", "double" -> ClassName.get(Double.class);
			default -> ClassName.get(String.class);
		};
	}
}
