package summer.aot.generator;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.lang.model.element.Modifier;
import org.jboss.jandex.AnnotationInstance;
import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.DotName;
import org.jboss.jandex.IndexView;
import org.jboss.jandex.MethodInfo;

/**
 * Generates an AOT {@code ExceptionHandlerRegistrar} that registers exception
 * handlers without reflection.
 */
public final class ExceptionHandlerAdapterGenerator {

	private static final ClassName EXCEPTION_HANDLER_REGISTRAR = ClassName.get("summer.web", "ExceptionHandlerRegistrar");
	private static final ClassName EXCEPTION_REGISTRY = ClassName.get("summer.web", "ExceptionRegistry");
	private static final ClassName BEAN_CONTAINER = ClassName.get("summer.core", "BeanContainer");
	private static final ClassName HANDLER = ClassName.get("summer.web", "Handler");
	private static final ClassName REQUEST_ATTRIBUTES = ClassName.get("summer.web", "RequestAttributes");

	private static final DotName EXCEPTION_HANDLER_DOT = DotName.createSimple("summer.web.annotation.ExceptionHandler");

	/**
	 * Generate an AOT ExceptionHandlerRegistrar for the given beans.
	 *
	 * @param beans
	 *            bean definitions to scan for @ExceptionHandler methods
	 * @param index
	 *            Jandex index
	 * @param outputDir
	 *            directory to write the generated source file
	 */
	public void generate(List<BeanDefinition> beans, IndexView index, File outputDir) throws IOException {
		CodeBlock.Builder registerBody = CodeBlock.builder();
		boolean hasHandlers = false;

		for (BeanDefinition bean : beans) {
			ClassInfo ci = index.getClassByName(DotName.createSimple(bean.qualifiedName));
			if (ci == null)
				continue;

			boolean hasHandlersForBean = false;
			for (MethodInfo method : ci.methods()) {
				AnnotationInstance ann = method.annotation(EXCEPTION_HANDLER_DOT);
				if (ann == null)
					continue;

				hasHandlers = true;
				String exceptionType = ann.value().asClass().name().toString();
				ClassName exceptionClass = TypeNameUtil.classNameFromString(exceptionType);
				String varName = bean.variableName;

				if (!hasHandlersForBean) {
					hasHandlersForBean = true;
					registerBody.add("$T $N = context.getBean($T.class)\n",
							TypeNameUtil.classNameFromString(bean.qualifiedName), varName,
							TypeNameUtil.classNameFromString(bean.qualifiedName));
					registerBody.add(";\n");
				}
				registerBody.add("registry.register($T.class, ctx -> {\n", exceptionClass);
				registerBody.indent();
				registerBody.add("$T ex = ($T) ctx.request().getAttribute($T.LAST_EXCEPTION)\n",
						exceptionClass, exceptionClass, REQUEST_ATTRIBUTES);
				registerBody.add(";\n");

				// Build method call — inspect each parameter's type
				StringBuilder args = new StringBuilder();
				for (int i = 0; i < method.parametersCount(); i++) {
					if (i > 0)
						args.append(", ");
					String paramTypeName = method.parameterType(i).name().toString();
					if ("summer.web.HttpContext".equals(paramTypeName)
							|| "summer.web.WebContext".equals(paramTypeName)) {
						args.append("ctx");
					} else if (isThrowable(index, paramTypeName)) {
						args.append("ex");
					} else {
						args.append("ex");
					}
				}
				registerBody.add("$N.$N($L)\n", varName, method.name(), args.toString());
				registerBody.add(";\n");
				registerBody.unindent();
				registerBody.add("})\n");
				registerBody.add(";\n");
			}
		}

		if (!hasHandlers)
			return;

		TypeSpec adapterClass = TypeSpec.classBuilder("GeneratedExceptionHandlerAdapter")
				.addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addSuperinterface(EXCEPTION_HANDLER_REGISTRAR)
				.addMethod(MethodSpec.methodBuilder("registerHandlers")
						.addAnnotation(Override.class)
						.addModifiers(Modifier.PUBLIC)
						.addParameter(EXCEPTION_REGISTRY, "registry")
						.addParameter(BEAN_CONTAINER, "context")
						.addCode(registerBody.build())
						.build())
				.build();

		JavaFile.builder("summer.core.aot", adapterClass)
				.addFileComment("Auto-generated by summer-maven-plugin. Do not edit!")
				.indent("    ")
				.build()
				.writeTo(outputDir);
	}

	private static boolean isThrowable(IndexView index, String typeName) {
		ClassInfo ci = index.getClassByName(DotName.createSimple(typeName));
		if (ci == null)
			return false;
		DotName current = ci.superName();
		while (current != null) {
			if (current.toString().equals("java.lang.Throwable"))
				return true;
			ClassInfo superClass = index.getClassByName(current);
			if (superClass == null)
				break;
			current = superClass.superName();
		}
		return "java.lang.Throwable".equals(typeName);
	}
}
