package summer.compiler;

import com.palantir.javapoet.*;
import java.io.IOException;
import java.util.*;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.lang.model.element.Modifier;
import javax.tools.Diagnostic;

/**
 * Generates a {@code GeneratedAotContext} class that implements
 * {@code ApplicationContext}, wiring all discovered beans at compile time.
 */
final class AotContextGenerator {

	static final String PACKAGE = "summer.core.aot";
	static final String CLASS_NAME = "GeneratedAotContext";

	private static final ClassName APPLICATION_CONTEXT = ClassName.get("summer.core", "ApplicationContext");
	private static final ClassName SUMMER_EXCEPTION = ClassName.get("summer.core", "SummerException");
	private static final ClassName ERROR_CODE = ClassName.get("summer.core", "ErrorCode");

	private final Filer filer;
	private final Messager messager;

	AotContextGenerator(Filer filer, Messager messager) {
		this.filer = filer;
		this.messager = messager;
	}

	void generate(List<AptBeanDefinition> sortedBeans, boolean hasWeb) {
		TypeSpec contextClass = TypeSpec.classBuilder(CLASS_NAME).addModifiers(Modifier.PUBLIC, Modifier.FINAL)
				.addSuperinterface(APPLICATION_CONTEXT)
				.addJavadoc("Auto-generated AOT context. Do not edit manually!\n")
				.addJavadoc("Generated by summer-compiler at compile time.\n").addField(buildSingletonsField())
				.addField(buildCloseablesField()).addMethod(buildConstructor())
				.addMethod(buildWireMethod(sortedBeans, hasWeb)).addMethod(buildGetBean())
				.addMethod(buildGetBeansOfType()).addMethod(buildGetComponentClasses()).addMethod(buildDestroy())
				.build();

		JavaFile javaFile = JavaFile.builder(PACKAGE, contextClass)
				.addFileComment("Auto-generated by summer-compiler. Do not edit!").indent("    ").build();

		try {
			javaFile.writeTo(filer);

			// Generate META-INF/services/summer.core.ApplicationContext for ServiceLoader
			javax.tools.FileObject serviceFile = filer.createResource(javax.tools.StandardLocation.CLASS_OUTPUT, "",
					"META-INF/services/" + APPLICATION_CONTEXT.canonicalName());
			try (java.io.Writer w = serviceFile.openWriter()) {
				w.write(PACKAGE + "." + CLASS_NAME + "\n");
			}

			messager.printMessage(Diagnostic.Kind.NOTE,
					"[Summer AOT] Generated " + PACKAGE + "." + CLASS_NAME + " with " + sortedBeans.size() + " beans");
		} catch (IOException e) {
			messager.printMessage(Diagnostic.Kind.ERROR, "Failed to write GeneratedAotContext: " + e.getMessage());
		}
	}

	// -----------------------------------------------------------------------
	// Fields
	// -----------------------------------------------------------------------

	private FieldSpec buildSingletonsField() {
		ParameterizedTypeName mapType = ParameterizedTypeName.get(ClassName.get(Map.class),
				ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)),
				ClassName.get(Object.class));

		return FieldSpec.builder(mapType, "singletons", Modifier.PRIVATE, Modifier.FINAL)
				.initializer("new $T<>()", LinkedHashMap.class).build();
	}

	private FieldSpec buildCloseablesField() {
		ParameterizedTypeName listType = ParameterizedTypeName.get(ClassName.get(List.class),
				ClassName.get(AutoCloseable.class));

		return FieldSpec.builder(listType, "closeables", Modifier.PRIVATE, Modifier.FINAL)
				.initializer("new $T<>()", ArrayList.class).build();
	}

	// -----------------------------------------------------------------------
	// Constructor
	// -----------------------------------------------------------------------

	private MethodSpec buildConstructor() {
		return MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC).addStatement("wire()").build();
	}

	// -----------------------------------------------------------------------
	// wire() — the core instantiation method
	// -----------------------------------------------------------------------

	private MethodSpec buildWireMethod(List<AptBeanDefinition> sortedBeans, boolean hasWeb) {
		MethodSpec.Builder wire = MethodSpec.methodBuilder("wire").addModifiers(Modifier.PRIVATE);

		for (int i = 0; i < sortedBeans.size(); i++) {
			AptBeanDefinition bean = sortedBeans.get(i);
			ClassName beanClass = ClassName.bestGuess(bean.qualifiedName());
			String var = bean.variableName;

			if (i > 0) {
				wire.addCode("\n");
			}

			switch (bean.kind) {
				case COMPONENT, CONFIGURATION -> emitComponentInstantiation(wire, bean, beanClass, var);
				case FACTORY_PRODUCT -> emitFactoryProductInstantiation(wire, bean, var);
			}

			// Register in singletons map
			if (bean.needsProxy) {
				// Concrete key → raw instance (proxy can't be cast to concrete class)
				wire.addStatement("singletons.put($T.class, $N)", beanClass, var + "_impl");
			} else {
				wire.addStatement("singletons.put($T.class, $N)", beanClass, var);
			}
			for (String iface : bean.interfaceNames()) {
				wire.addStatement("singletons.putIfAbsent($T.class, $N)", ClassName.bestGuess(iface), var);
			}

			if (bean.isAutoCloseable) {
				wire.addStatement("closeables.add($N)", var);
			}
		}

		if (hasWeb) {
			wire.addCode("\n");
			wire.addStatement(
					"summer.web.RouteRegistrar routeRegistrar = new summer.core.aot.GeneratedAnnotationRouterAdapter(\n"
							+ "    (summer.web.Router) singletons.get(summer.web.Router.class),\n" + "    this,\n"
							+ "    (summer.web.ExceptionRegistry) singletons.get(summer.web.ExceptionRegistry.class)\n"
							+ ")");
			wire.addStatement("singletons.put(summer.web.RouteRegistrar.class, routeRegistrar)");
		}

		return wire.build();
	}

	private void emitComponentInstantiation(MethodSpec.Builder wire, AptBeanDefinition bean, ClassName beanClass,
			String var) {
		CodeBlock args = buildConstructorArgs(bean);

		if (bean.needsProxy) {
			String implVar = var + "_impl";
			if (bean.constructorParamTypes().isEmpty()) {
				wire.addStatement("$T $N = new $T()", beanClass, implVar, beanClass);
			} else {
				wire.addStatement("$T $N = new $T($L)", beanClass, implVar, beanClass, args);
			}

			String interceptorsListVar = var + "_interceptors";
			wire.addStatement("$T<$T> $N = new $T<>()", ClassName.get(List.class),
					ClassName.get("summer.aop", "MethodInterceptor"), interceptorsListVar,
					ClassName.get(ArrayList.class));

			for (AptBeanDefinition interceptor : bean.interceptors) {
				wire.beginControlFlow("if ($N.supports($T.class))", interceptor.variableName, beanClass)
						.addStatement("$N.add($N)", interceptorsListVar, interceptor.variableName).endControlFlow();
			}

			TypeName proxyType = bean.interfaceNames().isEmpty()
					? beanClass
					: ClassName.bestGuess(bean.interfaceNames().get(0));
			ClassName proxyClass = ClassName.get(beanClass.packageName(), beanClass.simpleName() + "$$AotProxy");
			wire.addStatement("$T $N = new $T($N, $N)", proxyType, var, proxyClass, implVar, interceptorsListVar);
		} else {
			if (bean.constructorParamTypes().isEmpty()) {
				wire.addStatement("$T $N = new $T()", beanClass, var, beanClass);
			} else {
				wire.addStatement("$T $N = new $T($L)", beanClass, var, beanClass, args);
			}
		}
	}

	private CodeBlock buildConstructorArgs(AptBeanDefinition bean) {
		CodeBlock.Builder args = CodeBlock.builder();
		int depIdx = 0;
		List<String> paramTypes = bean.constructorParamTypes();
		for (int i = 0; i < paramTypes.size(); i++) {
			if (i > 0)
				args.add(", ");
			String type = paramTypes.get(i);
			if (type.equals("summer.core.ApplicationContext")) {
				args.add("this");
			} else {
				if (depIdx < bean.resolvedDependencies.size()) {
					args.add("$N", bean.resolvedDependencies.get(depIdx).variableName);
					depIdx++;
				} else {
					args.add("null");
				}
			}
		}
		return args.build();
	}

	private void emitFactoryProductInstantiation(MethodSpec.Builder wire, AptBeanDefinition bean, String var) {
		ClassName producedClass = ClassName.bestGuess(bean.qualifiedName());
		String configVar = bean.configBeanDefinition.variableName;
		// For AptBeanDefinition, we need the method name. For now, use a convention.
		String methodName = "unknown"; // Will be set properly for AptBeanDefinition
		if (bean instanceof AptBeanDefinition apt && apt.producerMethod != null) {
			methodName = apt.producerMethod.getSimpleName().toString();
		}
		CodeBlock args = buildArgs(bean.resolvedDependencies);

		if (bean.producerParamTypes().isEmpty()) {
			wire.addStatement("$T $N = $N.$N()", producedClass, var, configVar, methodName);
		} else {
			wire.addStatement("$T $N = $N.$N($L)", producedClass, var, configVar, methodName, args);
		}
	}

	private CodeBlock buildArgs(List<AptBeanDefinition> deps) {
		CodeBlock.Builder args = CodeBlock.builder();
		for (int i = 0; i < deps.size(); i++) {
			if (i > 0)
				args.add(", ");
			args.add("$N", deps.get(i).variableName);
		}
		return args.build();
	}

	// -----------------------------------------------------------------------
	// ApplicationContext method implementations
	// -----------------------------------------------------------------------

	private MethodSpec buildGetBean() {
		TypeVariableName typeVar = TypeVariableName.get("T");

		return MethodSpec.methodBuilder("getBean").addAnnotation(Override.class)
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addModifiers(Modifier.PUBLIC).addTypeVariable(typeVar).returns(typeVar)
				.addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), typeVar), "type")
				.addStatement("$T bean = singletons.get(type)", Object.class).beginControlFlow("if (bean != null)")
				.addStatement("return (T) bean").endControlFlow()
				.addStatement("throw new $T($T.BEAN_NOT_FOUND, $S + type.getName())", SUMMER_EXCEPTION,
						ERROR_CODE, "No bean found of type: ")
				.build();
	}

	private MethodSpec buildGetBeansOfType() {
		TypeVariableName typeVar = TypeVariableName.get("T");

		return MethodSpec.methodBuilder("getBeansOfType").addAnnotation(Override.class)
				.addAnnotation(
						AnnotationSpec.builder(SuppressWarnings.class).addMember("value", "$S", "unchecked").build())
				.addModifiers(Modifier.PUBLIC).addTypeVariable(typeVar)
				.returns(ParameterizedTypeName.get(ClassName.get(List.class), typeVar))
				.addParameter(ParameterizedTypeName.get(ClassName.get(Class.class), typeVar), "type")
				.addStatement("return singletons.values().stream()\n"
						+ "    .filter(type::isInstance).map(v -> (T) v).toList()")
				.build();
	}

	private MethodSpec buildGetComponentClasses() {
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(Set.class),
				ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)));

		return MethodSpec.methodBuilder("getComponentClasses").addAnnotation(Override.class)
				.addModifiers(Modifier.PUBLIC).returns(returnType).addStatement("return singletons.keySet()").build();
	}

	private MethodSpec buildDestroy() {
		return MethodSpec.methodBuilder("destroy").addAnnotation(Override.class).addModifiers(Modifier.PUBLIC)
				.addStatement("var reversed = new $T<>(closeables)", ArrayList.class)
				.addStatement("$T.reverse(reversed)", Collections.class).beginControlFlow("for (var c : reversed)")
				.beginControlFlow("try").addStatement("c.close()").nextControlFlow("catch ($T e)", Exception.class)
				.addStatement("$T.err.println($S + e)", System.class, "[Summer] Error closing: ").endControlFlow()
				.endControlFlow().build();
	}
}
