package summer.scanner.runtime;

import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.jar.JarFile;
import java.util.zip.ZipEntry;
import org.jboss.jandex.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import summer.core.Component;
import summer.core.ErrorCode;
import summer.core.SummerException;
import summer.core.annotation.Replaces;
import summer.core.exception.BeanCreationException;
import summer.core.exception.DuplicateReplacementException;

/**
 * Component scanner that discovers Summer components using Jandex indexes. All
 * modules (framework and user) ship pre-built {@code META-INF/jandex.idx} files
 * generated by the {@code jandex-maven-plugin}. User packages without an index
 * are scanned on-the-fly as a development fallback.
 */
public class ComponentScanner {

	private static final Logger log = LoggerFactory.getLogger(ComponentScanner.class);

	private static final DotName COMPONENT = DotName.createSimple(Component.class);

	private final Set<Class<?>> componentClasses = new HashSet<>();

	/**
	 * Discovers @Component-annotated classes (including meta-annotations
	 * like @Configuration, @RestController, @GlobalMiddleware). Framework beans
	 * come from pre-built Jandex indexes; user beans are discovered by indexing the
	 * given packages.
	 */
	public void scan(String... packageNames) {
		IndexView index = buildIndex(packageNames);
		registerDiscoveredBeans(index);
		// Register Jandex-based RowMapperFactory for runtime RowMapper creation
		JandexRowMapperFactory.registerIfPossible(index);
	}

	private IndexView buildIndex(String... packageNames) {
		Indexer indexer = new Indexer();

		// 1. Index user packages
		for (String packageName : packageNames) {
			indexUserPackage(indexer, packageName);
		}

		Index userIndex = indexer.complete();

		// 2. Load pre-built framework indexes
		List<Index> frameworkIndexes = loadFrameworkIndexes();

		if (frameworkIndexes.isEmpty()) {
			return userIndex;
		}

		// 3. Merge: user + framework
		List<IndexView> allIndexes = new ArrayList<>();
		allIndexes.add(userIndex);
		allIndexes.addAll(frameworkIndexes);
		return CompositeIndex.create(allIndexes);
	}

	/**
	 * Indexes user packages at runtime. Handles both file: and jar: classpath
	 * entries.
	 */
	private void indexUserPackage(Indexer indexer, String packageName) {
		String packagePath = packageName.replace('.', '/');
		try {
			Enumeration<URL> resources = getClass().getClassLoader().getResources(packagePath);
			while (resources.hasMoreElements()) {
				URL resource = resources.nextElement();
				if ("file".equals(resource.getProtocol())) {
					try {
						Path dir = Paths.get(resource.toURI());
						if (Files.isDirectory(dir)) {
							indexDirectory(indexer, dir);
						}
					} catch (URISyntaxException e) {
						log.debug("[Summer] Could not convert URL to path: {}", resource);
					}
				} else if ("jar".equals(resource.getProtocol())) {
					tryIndexJar(indexer, resource);
				}
			}
		} catch (IOException e) {
			log.warn("[Summer] Failed to index package {}: {}", packageName, e.getMessage());
		}
	}

	private void indexDirectory(Indexer indexer, Path dir) throws IOException {
		try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir, "*.class")) {
			for (Path classFile : stream) {
				try (InputStream is = Files.newInputStream(classFile)) {
					indexer.index(is);
				}
			}
		}
		try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
			for (Path entry : stream) {
				if (Files.isDirectory(entry)) {
					indexDirectory(indexer, entry);
				}
			}
		}
	}

	private void tryIndexJar(Indexer indexer, URL url) {
		String urlStr = url.toString();
		if (!urlStr.startsWith("jar:file:"))
			return;
		String jarPath = urlStr.substring("jar:file:".length());
		int bangIndex = jarPath.indexOf('!');
		if (bangIndex > 0)
			jarPath = jarPath.substring(0, bangIndex);

		try (JarFile jar = new JarFile(jarPath)) {
			String prefix = urlStr.substring(urlStr.indexOf('!') + 2);
			Enumeration<? extends ZipEntry> entries = jar.entries();
			while (entries.hasMoreElements()) {
				ZipEntry entry = entries.nextElement();
				if (entry.getName().startsWith(prefix) && entry.getName().endsWith(".class") && !entry.isDirectory()) {
					try (InputStream is = jar.getInputStream(entry)) {
						indexer.index(is);
					}
				}
			}
		} catch (IOException e) {
			log.debug("[Summer] Could not index JAR {}: {}", jarPath, e.getMessage());
		}
	}

	/**
	 * Loads pre-built {@code META-INF/jandex.idx} files from all framework JARs on
	 * the classpath.
	 */
	private List<Index> loadFrameworkIndexes() {
		List<Index> indexes = new ArrayList<>();
		try {
			Enumeration<URL> urls = getClass().getClassLoader().getResources("META-INF/jandex.idx");
			while (urls.hasMoreElements()) {
				URL url = urls.nextElement();
				try (InputStream is = url.openStream()) {
					indexes.add(new IndexReader(is).read());
				} catch (IOException e) {
					log.debug("[Summer] Failed to read jandex.idx from {}: {}", url, e.getMessage());
				}
			}
		} catch (IOException e) {
			log.warn("[Summer] Failed to enumerate jandex.idx resources: {}", e.getMessage());
		}
		return indexes;
	}

	/**
	 * Queries the merged index for classes annotated with @Component (directly or
	 * via recursive meta-annotation), then loads and registers them.
	 */
	private void registerDiscoveredBeans(IndexView index) {
		for (ClassInfo classInfo : index.getKnownClasses()) {
			if (classInfo.isInterface() || classInfo.isAbstract())
				continue;

			// Skip AOT-generated Provider classes (config.generated package)
			String className = classInfo.name().toString();
			if (className.contains(".config.generated.") || className.contains("$Generated")) {
				continue;
			}

			if (isBeanClass(classInfo, index)) {
				try {
					componentClasses.add(Class.forName(className));
				} catch (ClassNotFoundException e) {
					log.debug("[Summer] Could not load indexed class: {}", classInfo.name());
				}
			}
		}
		log.debug("[Summer] Registered {} component classes", componentClasses.size());
	}

	/**
	 * Checks if a class is a bean: annotated with @Component (directly or via
	 * recursive meta-annotation chain).
	 * Covers @Configuration, @RestController, @GlobalMiddleware, and any future
	 * annotations meta-annotated with @Component.
	 */
	private boolean isBeanClass(ClassInfo classInfo, IndexView index) {
		return hasComponentMetaAnnotation(classInfo, index, new HashSet<>());
	}

	private boolean hasComponentMetaAnnotation(ClassInfo classInfo, IndexView index, Set<DotName> visited) {
		if (classInfo == null)
			return false;
		DotName name = classInfo.name();
		if (!visited.add(name))
			return false; // cycle guard

		if (classInfo.hasAnnotation(COMPONENT))
			return true;

		// Bug fix: use classAnnotations() instead of annotations().
		// annotations() returns ALL annotations on the class and its members
		// (fields, methods, constructors), which could cause a field/method-level
		// annotation to be falsely treated as a meta-annotation on the class itself.
		// classAnnotations() is scoped to the class declaration only.
		for (AnnotationInstance ann : classInfo.classAnnotations()) {
			if (hasComponentMetaAnnotation(index.getClassByName(ann.name()), index, visited)) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Adds a component class directly.
	 */
	public void registerComponent(Class<?> clazz) {
		if (!isComponent(clazz)) {
			throw new BeanCreationException(ErrorCode.BEAN_CREATION_FAILED,
					"Class " + clazz.getName() + " is not annotated with @Component");
		}
		componentClasses.add(clazz);
	}

	/**
	 * Checks if a class is a component, including meta-annotated components.
	 */
	private boolean isComponent(Class<?> clazz) {
		if (clazz.isAnnotationPresent(Component.class))
			return true;
		for (java.lang.annotation.Annotation ann : clazz.getAnnotations()) {
			if (ann.annotationType().isAnnotationPresent(Component.class))
				return true;
		}
		return false;
	}

	/**
	 * Gets all registered component classes.
	 */
	public Set<Class<?>> getComponentClasses() {
		return componentClasses;
	}

	/**
	 * Resolves @Replaces annotations: finds all @Configuration classes that replace
	 * other configurations, validates no duplicate replacements, and removes
	 * replaced classes from the component set.
	 *
	 * @return the set of replaced configuration classes (so callers can also
	 *         exclude their @Bean producers)
	 */
	public Set<Class<?>> resolveReplacements() {
		Map<Class<?>, Class<?>> replacementMap = new HashMap<>(); // replaced -> replacement

		for (Class<?> clazz : new ArrayList<>(componentClasses)) {
			Replaces replaces = clazz.getAnnotation(Replaces.class);
			if (replaces == null)
				continue;

			Class<?> target = replaces.value();

			if (replacementMap.containsKey(target)) {
				throw new DuplicateReplacementException(replacementMap.get(target), clazz, target);
			}

			if (!componentClasses.contains(target)) {
				throw new SummerException(ErrorCode.BEAN_CREATION_FAILED, "@Replaces target " + target.getName()
						+ " (on " + clazz.getName()
						+ ") is not a registered component. Ensure the target is annotated with @Configuration and in a scanned package.");
			}

			replacementMap.put(target, clazz);
		}

		// Remove replaced classes from component set
		for (Class<?> replaced : replacementMap.keySet()) {
			componentClasses.remove(replaced);
		}

		return replacementMap.keySet();
	}
}
