app:
  name: summer-tck-fixtures
  port: 8080
  verbose: true

tls:
  enabled: true
  cert-chain: /path/to/cert.pem
  private-key: /path/to/key.pem

server:
  tls:
    enabled: true
    cert-chain: /path/to/cert.pem
