// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EchoService.proto

package com.github.dropguard.summer.grpc.test.echo;

public interface EchoResponseOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:echo.EchoResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString getMessageBytes();
}
