package com.github.dropguard.summer.plugin;

import static java.nio.charset.StandardCharsets.UTF_8;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.github.dropguard.summer.core.BeanContainer;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Field;
import java.nio.file.Files;
import org.apache.maven.artifact.Artifact;
import org.apache.maven.artifact.DefaultArtifact;
import org.apache.maven.artifact.handler.DefaultArtifactHandler;
import org.apache.maven.model.Build;
import org.apache.maven.project.MavenProject;
import org.jboss.jandex.Index;
import org.jboss.jandex.Indexer;
import org.junit.jupiter.api.Test;

/**
 * End-to-end execution of the {@code generate-aot} mojo on a minimal fixture project.
 *
 * <p>The mojo's {@code @Parameter} fields are injected directly (no Maven-plugin-testing harness —
 * the harness's fake session yields an empty {@code project.getArtifacts()}, which is precisely the
 * classpath path under test). The compile classpath is the fixture's classes directory plus the
 * summer-core classes directory, so {@code compileGeneratedSources} exercises the same artifact
 * resolution a real build would.
 *
 * <p>The fixture's {@code jandex.idx} is produced in-test via the Jandex library (the same library
 * the third-party jandex-maven-plugin wraps), so the test constrains the Summer plugin's contract
 * without depending on the third-party plugin.
 */
class SummerMojoTest {

    @Test
    void executeGeneratesAotContextCompilesAndFlipsEngine() throws Exception {
        File basedir = Files.createTempDirectory("summer-mojo-test").toFile();
        File classes = new File(basedir, "target/classes");
        prepareFixture(classes);

        MavenProject project = new MavenProject();
        project.setGroupId("com.example");
        project.setArtifactId("fixture-app");
        project.setVersion("1.0");
        project.setPackaging("jar");
        project.setFile(new File(basedir, "pom.xml"));
        Build build = new Build();
        build.setDirectory(new File(basedir, "target").getAbsolutePath());
        build.setOutputDirectory(classes.getAbsolutePath());
        project.setBuild(build);
        project.getArtifacts().add(coreArtifact());

        SummerMojo mojo = new SummerMojo();
        setField(mojo, "project", project);
        setField(mojo, "outputDirectory", classes);

        mojo.execute();

        File generated =
                new File(
                        basedir,
                        "target/generated-sources/aot/"
                            + "com/github/dropguard/summer/aot/generated/GeneratedAotContext.java");
        assertTrue(
                generated.exists(),
                "the AOT context must be generated by the mojo, looking at: "
                        + generated.getAbsolutePath());

        String yml =
                new String(
                        Files.readAllBytes(new File(classes, "application.yml").toPath()), UTF_8);
        assertTrue(
                yml.contains("engine:") && yml.contains("aot"),
                "application.yml must be flipped to the AOT engine: " + yml);
    }

    /** Copies the fixture bean, writes its Jandex index, and seeds an application.yml. */
    private void prepareFixture(File classes) throws Exception {
        classes.mkdirs();
        File fixture = new File(classes, "com/github/dropguard/summer/plugin/FixtureService.class");
        fixture.getParentFile().mkdirs();
        try (InputStream in =
                getClass()
                        .getClassLoader()
                        .getResourceAsStream(
                                "com/github/dropguard/summer/plugin/FixtureService.class")) {
            Files.copy(in, fixture.toPath(), REPLACE_EXISTING);
        }

        Indexer indexer = new Indexer();
        try (InputStream in = new FileInputStream(fixture)) {
            indexer.index(in);
        }
        Index index = indexer.complete();
        File metaInf = new File(classes, "META-INF");
        metaInf.mkdirs();
        try (OutputStream out = new FileOutputStream(new File(metaInf, "jandex.idx"))) {
            new org.jboss.jandex.IndexWriter(out).write(index);
        }

        Files.write(
                new File(classes, "application.yml").toPath(),
                "name: fixture-app\n".getBytes(UTF_8));
    }

    /** The summer-core classes directory/jar, handed to the project as a compile artifact. */
    private Artifact coreArtifact() throws Exception {
        File core =
                new File(
                        BeanContainer.class
                                .getProtectionDomain()
                                .getCodeSource()
                                .getLocation()
                                .toURI());
        DefaultArtifact artifact =
                new DefaultArtifact(
                        "com.github.dropguard",
                        "summer-core",
                        "0.1.0",
                        "compile",
                        "jar",
                        null,
                        new DefaultArtifactHandler("jar"));
        artifact.setFile(core);
        return artifact;
    }

    private static void setField(Object target, String name, Object value) throws Exception {
        Field f = SummerMojo.class.getDeclaredField(name);
        f.setAccessible(true);
        f.set(target, value);
    }
}
