// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.3
package summer.example.grpc;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_summer_example_grpc_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_summer_example_grpc_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_summer_example_grpc_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_summer_example_grpc_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_summer_example_grpc_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_summer_example_grpc_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\023summer.example.grpc\"\034\n\016Get" +
      "UserRequest\022\n\n\002id\030\001 \001(\t\"0\n\021CreateUserReq" +
      "uest\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\"7\n\014Use" +
      "rResponse\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005e" +
      "mail\030\003 \001(\t2\275\001\n\017UserGrpcService\022Q\n\007GetUse" +
      "r\022#.summer.example.grpc.GetUserRequest\032!" +
      ".summer.example.grpc.UserResponse\022W\n\nCre" +
      "ateUser\022&.summer.example.grpc.CreateUser" +
      "Request\032!.summer.example.grpc.UserRespon" +
      "seB\027\n\023summer.example.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_summer_example_grpc_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_summer_example_grpc_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_summer_example_grpc_GetUserRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_summer_example_grpc_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_summer_example_grpc_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_summer_example_grpc_CreateUserRequest_descriptor,
        new java.lang.String[] { "Name", "Email", });
    internal_static_summer_example_grpc_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_summer_example_grpc_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_summer_example_grpc_UserResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
